#!/usr/bin/env node
import { resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { scan } from "./scan.js";
import { json, mermaid, sarif, text } from "./report.js";

function help(): void { process.stdout.write(["Repo Context Doctor - inspect effective coding-agent instructions", "", "Usage:", "  context-doctor [path] [options]", "  context-doctor graph [path] --mermaid", "", "Options:", "  --agent codex|claude|cursor  Limit the provider", "  --cwd <path>                Resolve nested scope", "  --json                      Emit versioned JSON", "  --sarif                     Emit SARIF for code scanning", "  --mermaid                   Emit a Mermaid source graph", "  --strict                    Treat warnings as blocking", "  --help                      Show help", ""].join("\n")); }
export async function main(argv = process.argv.slice(2)): Promise<number> { if (argv.includes("--help") || argv.includes("-h")) { help(); return 0; } const positional = argv.filter((a) => !a.startsWith("-")); const command = positional[0] === "graph" || positional[0] === "check" ? positional[0] : "check"; const pathArg = positional[0] === command ? positional[1] : positional[0]; const agentIndex = argv.indexOf("--agent"); const cwdIndex = argv.indexOf("--cwd"); try { const result = await scan(resolve(pathArg ?? "."), cwdIndex >= 0 ? argv[cwdIndex + 1] ?? "." : ".", agentIndex >= 0 ? argv[agentIndex + 1] as "codex" | "claude" | "cursor" : undefined); process.stdout.write(argv.includes("--mermaid") ? mermaid(result) : argv.includes("--sarif") ? sarif(result) : argv.includes("--json") ? json(result) : text(result)); return command === "graph" ? 0 : result.findings.some((f) => f.severity === "error" || (argv.includes("--strict") && f.severity === "warning")) ? 1 : 0; } catch (error) { process.stderr.write(`context-doctor: ${error instanceof Error ? error.message : "tool failure"}\n`); return 3; } }
if (process.argv[1] && fileURLToPath(import.meta.url) === resolve(process.argv[1])) main().then((code) => { process.exitCode = code; });
